version: "3.9"
services:
  neo4j:
    image: neo4j
    ports:
        - 7474:7474
        - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=none